name: Build on Debian Trixie

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker images
        uses: docker/build-push-action@v5
        with:
           file: docker/debian/Dockerfile_trixie
           load: true
           tags: cgimap:trixie
      - name: Running Docker image
        run: |
           docker run --entrypoint /bin/bash cgimap:trixie -c "/usr/local/bin/openstreetmap-cgimap --help"

