name: Build on Debian Trixie

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        uses: docker/build-push-action@v6
        with:
           file: docker/debian/Dockerfile_trixie
           load: true
           cache-from: type=gha,scope=cgimap:trixie
           cache-to: type=gha,mode=max,scope=cgimap:trixie
           tags: cgimap:trixie

      - name: Running Docker image
        run: |
           docker run --entrypoint /bin/bash cgimap:trixie -c "/usr/local/bin/openstreetmap-cgimap --help"

