name: Build on Debian Bookworm

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        uses: docker/build-push-action@v6
        with:
           file: docker/debian/Dockerfile_bookworm
           load: true
           cache-from: type=gha,scope=cgimap:bookworm
           cache-to: type=gha,mode=max,scope=cgimap:bookworm
           tags: cgimap:bookworm

      - name: Running Docker image
        run: |
           docker run --entrypoint /bin/bash cgimap:bookworm -c "/usr/local/bin/openstreetmap-cgimap --help"
